version: '3'
services:
  web:
    container_name: web
    volumes:
     - './:/var/www/html'
    build: .
    ports:
          - '80:80'
          - '443:443'

  percona:
    container_name: percona
    image: percona
    environment:
        MYSQL_ROOT_PASSWORD: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
        MYSQL_DATABASE: symfony
    volumes:
      - './docker/percona/sql:/var/lib/mysql'
    ports:
      - '3306:3306'
    restart: always

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=172.18.0.1
          - PMA_PORT=3306
        restart: always
        ports:
         - '8082:80'
        volumes:
         - /sessions